### ISSUE TITLE
MongoDB Implementation for SettingsGateway

### ISSUE THREAD

**Issue by tale** [Emy/filo#42]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Implement MongoDB, as SettingsGateway provider as it will have better performance under multiple guilds, clients, and users

**Describe alternatives you've considered**
Current system, which I believe is JSON or SQLite

**Additional context**
This will allow for easier implementation of Moderation commands

Provider:
https://github.com/dirigeants/klasa-pieces/blob/master/providers/mongodb.js

**Comment by emy** [comment]
It'll be the same effort for inserting settings... It's not different from adding settings to the json provider.
I'll have a look which DBMS filo will be using in the future.

**Comment by tale** [comment]
Hmm, okay, however If we really want to continue with Moderation, we are gonna need a solution soon

**Comment by 1Conan** [comment]
1. Don't use MongoDB. Much better alternatives like Rethink.
2. This shouldn't be a priority as Filo isn't using SG yet.
3. JSON provider is perfectly fine for current use which is just schedules from what I see.
