### ISSUE TITLE
Question / Request: Avatar picture format

### ISSUE THREAD

**Issue by emy** [Emy/filo#5]
**Is your feature request related to a problem? Please describe.**
The current whois command uses the avatarURL() funtion which returns a link to a .webp link.
Since not every platform is capable to display .webp image we should consider either removing the avatars completely, switching to a more compatible format or just wait until .webp is either adopted or abandoned.

**Describe the solution you'd like**

- Wait until vendors add or abandon .webp
- Use .png (preferred) or .jpg (not preferred)
- Remove all avatars

**Describe alternatives you've considered**
As above.

**Additional context**
Pls discuss.

**Comment by fluffylea** [comment]
**Here a small comparison between the formats based on my Avatar:**

Keep in mind that bigger file sizes might be bad for those with limited data.

Format|Size|Compression|Compatibility
-------|----|----|---------
png    |  29 KB | Lossless |Everywhere
jpg     |  3.2 KB | Lossy | Everywhere
webp |  2.2 KB | Lossy | Chromium *)

*) The Discord client and Chrome are based on Chromium. It does work there. It does not work on iOS (including the App), Safari, Firefox and Edge (for those using Discord in the Browser.)

**Comment by emy** [comment]
I decided i'm going with png as the format of choice now! Closing this issue.
