### ISSUE TITLE
Users cannot ban Revulate

### ISSUE THREAD

**Issue by SparkDev97** [Emy/filo#87]
**Describe the bug**
Users cannot ban Revulate

**To Reproduce**
1. Go to server
2. Be a user
3. Try to ban Revulate 

**Expected behavior**
Revulate is banned until the end of time

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: 14 beta 1

**Additional context**
I’m lost in a desert, please help me.

**Comment by emy** [comment]
We will dedicate all our resources into fixing this critical bug! Thanks for the report!
